Update sevpn

diff --git a/sevpn b/sevpn
--- a/sevpn
+++ b/sevpn
@@ -3,18 +3,18 @@ PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
 export PATH
 myfile=/usr/bin/sevpn
 nettools=/bin/netstat
-address=xxoo.sedns.cn
+#赋值
+address=https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.29-9680-rtm
 rm -rf sevpn
 clear
-
-
+#安装组件
 if [ ! -f $nettools ]; then 
-    echo "缺少组件,正在安装...骚等!"
+    echo "正在安装组件!"
 	yum install net-tools -y >/dev/null 2>&1
 	apt-get install net-tools -y >/dev/null 2>&1
 fi
-
 rm -rf sevpn* >/dev/null 2>&1
+#检测IP
 function check_ip(){
 IP=`wget http://members.3322.org/dyndns/getip -O - -q; echo`
     if [[ "$IP" == "" ]];then
@@ -22,13 +22,8 @@ IP=`wget http://members.3322.org/dyndns/getip -O - -q; echo`
     read IP
     fi
 }
-function rootness(){
-    if [[ $EUID -ne 0 ]]; then
-       echo "错误：请使用root用户进行安装!" 
-	   rm -rf sevpn* >/dev/null 2>&1
-       exit 1
-    fi
-}
+#检查是否为Root
+[ $(id -u) != "0" ] && { echo "Error: You must be root to run this script"; rm -rf sevpn* >/dev/null 2>&1; exit 1; }
 
 # Get version
 function getversion(){
@@ -90,15 +85,13 @@ function install_dep(){
         apt-get install gcc make expect unzip zip psmisc curl -y
 		apt-get install openssl -y
     fi
-
-
 }
-zewin=https://
+#download
 function set32(){
 rm -rf /vpnserver* >/dev/null 2>&1
 cd /
-wget ${address}/softether-vpnserver-v4.25-9656-rtm-2018.01.15-linux-x86-32bit.tar.gz
-tar -zxvf softether-vpnserver-v4.25-9656-rtm-2018.01.15-linux-x86-32bit.tar.gz
+wget ${address}/softether-vpnserver-v4.29-9680-rtm-2019.02.28-linux-x86-32bit.tar.gz
+tar -zxvf softether-vpnserver-v4.29-9680-rtm-2019.02.28-linux-x86-32bit.tar.gz
 rm -rf /softether-vpnserve*
 }
 
@@ -106,52 +99,47 @@ rm -rf /softether-vpnserve*
 function set64(){
 rm -rf /vpnserver* >/dev/null 2>&1
 cd /
-wget ${address}/softether-vpnserver-v4.25-9656-rtm-2018.01.15-linux-x64-64bit.tar.gz
-tar -zxvf softether-vpnserver-v4.25-9656-rtm-2018.01.15-linux-x64-64bit.tar.gz
+wget ${address}/softether-vpnserver-v4.29-9680-rtm-2019.02.28-linux-x64-64bit.tar.gz
+tar -zxvf softether-vpnserver-v4.29-9680-rtm-2019.02.28-linux-x64-64bit.tar.gz
 rm -rf /softether-vpnserve*
 }
 
 function get_ready(){
-echo -e "感谢使用一键Sevpn脚本,我是\033[40;31m 寂寞爱上海 \033[0m!"
-read -p "(回车将默认设置Sevpn管理密码为: yaohuo):" VPNPASSWD
-[ -z "$VPNPASSWD" ] && VPNPASSWD="yaohuo"
+read -p "请输入Sevpn管理密码(默认passwd):" VPNPASSWD
+[ -z "$VPNPASSWD" ] && VPNPASSWD="passwd"
 echo
 echo "---------------------------------------"
-echo "Ok，Sevpn管理密码已设置为 = $VPNPASSWD"
+echo "Sevpn管理密码已设置为: $VPNPASSWD"
 echo "---------------------------------------"
 echo
-echo -e "输入你要创建的VPN账号"
-read -p "(回车将默认设置VPN账号为：yaohuo):" USER
-[ -z "$USER" ] && USER="yaohuo"
+read -p "请输入创建的VPN账号(默认admin):" USER
+[ -z "$USER" ] && USER="admin"
 echo
 echo "---------------------------"
-echo "Ok，VPN账号已设置为 = $USER"
+echo "VPN账号已设置为: $USER"
 echo "---------------------------"
 echo
-echo -e "输入VPN账号的密码"
-read -p "(回车将默认设置相应$USER账号密码为：yaohuo):" USERPWD
-[ -z "$USERPWD" ] && USERPWD="yaohuo"
+read -p "请输入$USER账号密码(默认123456):" USERPWD
+[ -z "$USERPWD" ] && USERPWD="123456"
 echo
 echo "--------------------------------"
-echo "Ok，$USER密码已设置为 = $USERPWD"
+echo "$USER密码已设置为: $USERPWD"
 echo "--------------------------------"
 echo
 echo "SeVPN默认开启443TCP端口"
 echo "默认设置MP端口为: 8080(三网通)"
 
-echo -e "输入可以免流的host"
-read -p "(回车将默认设置相应自定义host为：vod3.nty.tv189.cn):" HOST
-[ -z "$HOST" ] && HOST="vod3.nty.tv189.cn"
+read -p "请输入伪装的域名(默认bing.com):" Domain
+[ -z "$Domain" ] && Domain="bing.com"
 echo
 echo "----------------------------------"
-echo "Ok，host已设置为 = $HOST"
+echo "伪装域名已设置为: $Domain"
 echo "----------------------------------"
 echo
-echo -e -n "\e[1;31m\n个人设置完毕,请按回车开始安装!\e[0m"
+echo -e -n "\e[1;31m\n配置结束,回车安装\e[0m"
 read
 }
-#安装sevpn
-zewinz=git.oschina.net
+#install sevpn
 function install_sevpn(){
     check_ip
     get_ready
@@ -165,7 +153,6 @@ killall -9 dhclient >/dev/null 2>&1
 rm -rf /vpnserver*
    download_files
 }
-ewinz=ml/raw/master
 function change_port(){
 cd /vpnserver
 ./vpnserver stop
@@ -173,7 +160,7 @@ cd /vpnserver
 
 ./vpnserver start
 }
-#下载文件
+#download files
 function download_files(){
 echo "正在判定系统 32位 OR 64位..."
     sleep 3
@@ -297,7 +284,6 @@ rm -f *l2.ovpn >/dev/null 2>&1
 sed -i "/# */d" sevpn.ovpn
 sed -i "/;http*/d" sevpn.ovpn
 sed -i "1a# 本文件由系统自动生成" sevpn.ovpn
-sed -i "2a# 本脚本由寂寞爱上海制作" sevpn.ovpn
 sed -i "15adhcp-option DNS 114.114.115.115" sevpn.ovpn
 sed -i "15adhcp-option DNS 114.114.114.114" sevpn.ovpn
 
@@ -321,8 +307,6 @@ sed -i "s/^proto.*/proto tcp/g" sevpn.ovpn
 #sed -i "15ihttp-proxy 119.39.227.247 18889" 18889.ovpn
 #sed -i "15iremote $IP 443" 18889.ovpn
 #sed -i "15i#全国联通直连18889" 18889.ovpn
-
-
 
 echo "生成酷视卡"
 cp sevpn.ovpn 酷视卡.ovpn
@@ -380,7 +364,6 @@ echo
 
 }
 
-zwein=/mproxy
 function cxall(){
 cd /vpnserver
 ./vpncmd <<EOF
@@ -714,7 +697,7 @@ killall -9 mproxy >/dev/null 2>&1
 rm -rf /vpnserver >/dev/null 2>&1
 rm -rf /usr/bin/sevpn >/dev/null 2>&1
 clear
-echo -e "\e[1;36m           成功卸载SeVPN!\e[0m"
+echo -e "\e[1;36mUninstall success!\e[0m"
 exit 1
 }
 rootness
